# TD 1 | Introduction à Python pour l'analyse de données

---

Objectifs du TD :

* découvrir Python
* se familiariser avec le langage et le notebook Jupyter
* découvrir et maîtriser les bases des librairies de calcul numérique et d'analyse de données numpy et pandas

---

##  Installation de Python et Jupyter

### Windows

#### Installation Python

Vérifiez si vous avez déjà une version de python installée en ouvrant l'invite de commande et en exécutant l'une des deux commandes python suivantes : 
> python --version   

> python3 --version 

Si ce n'est pas le cas, vous pouvez procéder à l'installation comme suit :
 
1. Allez sur le site web : https://www.python.org/downloads/windows/
2. Cliquez sur "Latest Python 3 Release - Python 3.10.7".
3. Si votre ordinateur utilise une version 64 bits de Windows, téléchargez le Windows installer (64-bit). Sinon, téléchargez Windows installer (32-bit).
4. Après avoir téléchargé le Windows installer, vous devez l'exécuter (double-cliquez dessus) et suivre les instructions qui s'y trouvent.

NB : Au début de l'installation, assurez-vous de cocher la case "Add Python 3.10 to PATH" ou "Add Python to your environment variables" avant de cliquer sur "Install Now".


#### Installation Jupyter

Ouvrir l'invite de commande et exécuter la commande suivante en remplaçant Pseudo_de_votre_user par le nom de l'utilisateur de votre session : 
> cd "C:\Users\Pseudo_de_votre_user\AppData\Local\Programs\Python\Python310\Scripts"

Ensuite, executer la commande suivante :
> pip install jupyterlab

Une fois l'installation terminée avec succès, vous pouvez lancer JupyterLab avec la commande suivante : 
> jupyter-lab


### Linux & Mac OS

#### Installation Python

Normalement, Python est préinstallé sur la quasi-totalité des distributions. Vous n'avez pas besoin de le réinstaller, mais vous pouvez mettre à jour la version si vous le souhaitez.

Vérifiez la version Python installée en exécutant l'une des deux commandes python suivantes sur votre terminal : 
> python --version   

> python3 --version 

#### Installation Jupyter

Vérifier que la commande pip3 est installée. Sinon, l'installer (exemple pour Debian/Ubuntu/Linux Mint, à adapter selon votre distribution) :

> sudo apt install python3-pip

Ensuite, installer JupyterLab en executant la commande suivante:
> pip3 install -U jupyterlab

Enfin, placez-vous dans votre dossier de travail et lancez un notebook :

> jupyter-lab

## Syntaxe et Concepts de base

In [14]:
a = 33
b = 9
c = 2.0

In [15]:
a+b

42

In [16]:
print(a+b)

42


In [17]:
type(a)

int

In [18]:
type(c)

float

In [19]:
a = 'hello'
type(a)

str

In [20]:
# Affiche les entiers pairs de 1 à 10
for i in range(1, 11):
    if i % 2 == 0:
        print(i)

2
4
6
8
10


### List

In [22]:
l = [1,2,3,4,4]

#### len, max, min

In [24]:
print('longueur de la liste =', len(l))
print("Valeur max de l =", max(l))
print("Valeur min de l =", min(l))

longueur de la liste = 5
Valeur max de l = 4
Valeur min de l = 1


#### Ajout d'un élément d'une liste

In [26]:
l.append(6)
l

[1, 2, 3, 4, 4, 6]

In [27]:
l = l+[7]
l

[1, 2, 3, 4, 4, 6, 7]

In [28]:
l+=[7]
l

[1, 2, 3, 4, 4, 6, 7, 7]

#### Modifier un élément

In [30]:
l[0] = 29
l

[29, 2, 3, 4, 4, 6, 7, 7]

In [31]:
l.insert(1,9)
l

[29, 9, 2, 3, 4, 4, 6, 7, 7]

#### Suppression des éléments d'une liste

In [33]:
l.remove(7)
l

[29, 9, 2, 3, 4, 4, 6, 7]

In [34]:
l.pop(2)
l

[29, 9, 3, 4, 4, 6, 7]

#### Trier une liste

In [36]:
l.sort(reverse=True)
print(l)

[29, 9, 7, 6, 4, 4, 3]


In [37]:
l_sorted = sorted(l)
print('Sorted list:', l_sorted)

Sorted list: [3, 4, 4, 6, 7, 9, 29]


#### Liste non homogène

In [39]:
l = [1, 'un', 2]
l.append('deux')
l += [3, 'trois']
print(type(l))
l

<class 'list'>


[1, 'un', 2, 'deux', 3, 'trois']

In [40]:
a = l[3], l[-1]
print(type(a))
a

<class 'tuple'>


('deux', 'trois')

In [41]:
a[0]

'deux'

In [42]:
[2**p for p in range(10)] # "Compréhension de liste"

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [43]:
# Liste des entiers pairs de 1 à 10
l = [i for i in range(1, 11) if i % 2 == 0]
print(l)

[2, 4, 6, 8, 10]


### Tuple

In [45]:
p = tuple(range(1,5))
print("p=", p)
print("p[0] = ", p[0])

p= (1, 2, 3, 4)
p[0] =  1


In [46]:
p = ([1,2],5)

print(p)

p[0][0] = 8

print(p)

([1, 2], 5)
([8, 2], 5)


In [47]:
# Les éléments du tuple sont fixes
#p[0] = 6

In [48]:
p1 = (1,2)
p2 = (2,1)

print(p1 == p2)

False


### Set

In [50]:
s = set((1,2,'l'))
print(s)

s = {4,5,9,9,9,9}
print(s)

{1, 2, 'l'}
{9, 4, 5}


In [51]:
#Ajout d'un élément au set
s.add(6)
print(s)

{9, 4, 5, 6}


In [52]:
#Suppression d'un élément du set
s.discard(5)
print(s)

{9, 4, 6}


In [53]:
s.clear()
print(s)

set()


In [54]:
A = {1,2,3,4,5}
B = {2,4,6,7}
C = {1,2,3}

In [55]:
#Intersection
print("Intersection de A et B =", A&B)

#Union
print("Union entre A et B =", A|B)

#Exclusion
print("Exclusion de B de A =", A-B)

#Différence symétrique
print("Diff sym. A et B =", A^B)

Intersection de A et B = {2, 4}
Union entre A et B = {1, 2, 3, 4, 5, 6, 7}
Exclusion de B de A = {1, 3, 5}
Diff sym. A et B = {1, 3, 5, 6, 7}


In [56]:
print("B est inclus strict dans A") if A>B else print(False)
print("C est inclus dans A") if A>=C else print(False)

False
C est inclus dans A


### Dictionary

In [58]:
# 1ère façon de créer un dictionnaire
dic = {"key1": "value1", "answer": 42}
# 2ème façon de créer un dictionnaire
dic2 = dict(key1="value1", answer=42)
# 3ème façon de créer un dictionnaire
dic3 = dict([("key1","value1"), ("answer",42)])
print(dic)
print(dic2)
print(dic3)

dic["answer"]

{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}


42

In [59]:
dic['new'] = [1,2,3]

In [60]:
dic.keys()

dict_keys(['key1', 'answer', 'new'])

In [61]:
dic.items()

dict_items([('key1', 'value1'), ('answer', 42), ('new', [1, 2, 3])])

In [62]:
dic.values()

dict_values(['value1', 42, [1, 2, 3]])

In [63]:
a,b,c = dic.items()
print(a)

('key1', 'value1')


## Programmation Orientée Objet

In [65]:
"""
Exemple de classe en Python
"""
class Moteur:
    
    # Constructeur
    def __init__(self, esn, panne=False):
        self.esn = esn
        self.panne = panne
    
    # Méthodes
    def dire_bonjour(self):
        print('Bonjour, mon numéro de série est ' + self.esn)
    
    def fonctionne(self):
        return not self.panne 
    

In [66]:
mot1 = Moteur('420912')
mot2 = Moteur(panne=True, esn='420913')

mot1.dire_bonjour()
print(mot1.fonctionne())

mot1.panne = True
print(mot1.fonctionne())

print('\n')
mot2.dire_bonjour()
print(mot2.fonctionne())

Bonjour, mon numéro de série est 420912
True
False


Bonjour, mon numéro de série est 420913
False


### Méthode récurcive vs Méthode itérative

In [68]:
# Méthode récursive
def fact1(n):
    if n == 0:
        return 1
    else:
        return n*fact1(n-1)

# Méthode itérative
def fact2(n):
    s=1
    for i in range(1,n+1):
        s*=i
    return s

print(fact1(5))
print(fact2(5))

120
120


In [69]:
"""
App.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.
"""

'\nApp.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.\n'

In [70]:
"""
App.1 : Correction
"""

#Méthode itérative
def pgcd1(a,b):
    while (a%b) != 0:
        s = a%b
        a = b
        b = s
    return b


#Méthode récurcive
def pgcd2(a,b):
    if a==b : return a 
    if a<b : a,b = b,a
    return pgcd2(a-b,b)

a = 230
b = 25

print("pgcd1(a,b) = ", pgcd1(a,b))
print("pgcd2(a,b) = ", pgcd2(a,b))

pgcd1(a,b) =  5
pgcd2(a,b) =  5


## Libraries

> pip install numpy pandas

> pip3 install -U numpy pandas

### Math

In [74]:
import math

In [75]:
x = 4

print("sqrt(x) =", math.sqrt(x))
print("cos(x) =", math.cos(x))
print("sin(x) =", math.sin(x))
print("factorial(x) =", math.factorial(x))

sqrt(x) = 2.0
cos(x) = -0.6536436208636119
sin(x) = -0.7568024953079282
factorial(x) = 24


### Numpy

In [77]:
import numpy as np

In [78]:
# Création d'un array à partir d'une liste
v = np.array([1.0, 2.0, 3.0])
# Création d'un array de taille (n,m) initialisé à 0
z = np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
# Taille d'un array
print(z.shape)
print(v.shape)

(3, 4)
(3,)


In [80]:
# Opérations courantes
A = np.ones((3,3)) + np.eye(3)
print('A = ', A)
print('Av = ', np.dot(A,v))
print('3*A = ', 3*A)
print('A*v = ', A*v)
print('A + 1 = ', A+1)
print('A + v = ', A+v)
print('A^2 = ', np.square(A))

A =  [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
Av =  [7. 8. 9.]
3*A =  [[6. 3. 3.]
 [3. 6. 3.]
 [3. 3. 6.]]
A*v =  [[2. 2. 3.]
 [1. 4. 3.]
 [1. 2. 6.]]
A + 1 =  [[3. 2. 2.]
 [2. 3. 2.]
 [2. 2. 3.]]
A + v =  [[3. 3. 4.]
 [2. 4. 4.]
 [2. 3. 5.]]
A^2 =  [[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


In [81]:
B = np.array([5, 2, 9, 1])

print(np.sort(B))

[1 2 5 9]


#### Compatif de performance : produit matriciel


In [83]:
import random

In [84]:
# Création d'une matrice aléatoire sous forme de liste de listes
taille = 2
A = [[random.random() for _ in range(taille)] for _ in range(taille)]

In [85]:
print(A)

[[0.8272847065448604, 0.7143446676065326], [0.5816708431935876, 0.7961542933637881]]


In [86]:
"""
EXERCICE - Afficher un tuple contenant les dimensions de la matrice A
"""
(len(A),len(A[0]))


        #raise NotImplementedError

(2, 2)

$$ (AB)_{ij} = \sum_k A_{ik} B_{kj} $$

In [88]:
"""
EXERCICE - Implémenter le produit matriciel de 2 matrices sous forme de listes de listes python
"""
def prodmath(A,B):
    A=np.array(A)
    B=np.array(B)
    B=B.T
    n=len(A[0])
    C=np.zeros((len(A),len(B[0])))
    for i in range(len(A)):
        for j in range(len(B[0])):
            C[i][j]=np.dot(A[i],(B[j]))
    return C  
            
#raise NotImplementedError

In [89]:
taille = 3
A= [[random.random() for _ in range(taille)] for _ in range(taille)]
B= [[random.random() for _ in range(taille)] for _ in range(taille)]
C=prodmath(A,B)

In [90]:
 #Vérification
Z = [[1, 2], [3, 4]]
result = prodmath(Z, Z)
expected = np.array([[7, 10], [15, 22]])

# Comparaison avec np.array_equal
assert np.array_equal(result, expected), "Les matrices ne sont pas égales"

print("Test réussi")

Test réussi


In [91]:
taille = 3000
A= [[random.random() for _ in range(taille)] for _ in range(taille)]

In [92]:
# Sortons le chronomètre
#%timeit prodmath(A, A);

In [93]:
# Et maintenant, avec numpy !
import numpy as np

In [94]:
A2 = np.array(A)
#print(A2);

In [95]:
#%timeit np.dot(A, A)

# EXERCICE - Remplissez le tableau suivant avec les durées d'exécution constatées :

(Conseil : pour la taille 3000, essayez UNIQUEMENT avec numpy)

Taille | Python | numpy
-------|--------|-------
30     | 28.6 us   | 2.16 us
300    | 309ms   | 19.5ms
3000   | XXX    | 2.75 s

###  Pandas

In [98]:
import pandas as pd
import os
import numpy as np

In [99]:
df_exemple = pd.DataFrame({"ESN": ["E420912", "E420913", "E420914"], "panne": [False, False, True]})
df_exemple

ESN  panne
0  E420912  False
1  E420913  False
2  E420914   True

#### Lecture et prétraitement de données


In [101]:
 os.getcwd()

'C:\\Users\\jalil\\OneDrive\\Desktop\\MACS3\\analyse_donnée\\MACS3_Stats_TDs\\TD1'

In [102]:
# Chargement d'un fichier CSV ou Excel
df = pd.read_csv("../data/Vol010.csv")
# Affichage des 5 premières lignes
df.head()

t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
0                  datenum   deg_C          _       _        %        %   
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1 VIB_CN2  \
0      %     %_RPM   psi        _  ...       _      _     DEG       _       _   
1    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
2    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
3    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
4    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   

  VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
0       _       _     DEG     lb/h  mach  
1     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN  7679.98  0.15  

[5 rows x 26 columns]

In [103]:
"""
EXERCICE - Dimensions d'un DataFrame
Affichez le nombre de colonnes et de ligne du DataFrame (indice : beaucoup de méthodes sont communes entre numpy et pandas)
"""
print('Nombre de colonnes :',df.shape[1] )
print('Nombre de lignes :',df.shape[0] )

Nombre de colonnes : 26
Nombre de lignes : 22945


In [104]:
df.size, len(df)

(596570, 22945)

In [105]:
df.columns

Index(['t', 'EGT_SEL', 'FLIGHT_MOD', 'FMV_SEL', 'HPTC_SEL', 'LPTC_SEL',
       'N1_SEL', 'N2_ACTSEL', 'OIL_P', 'OIL_TEMP', 'PS3_SEL', 'PT2_SEL',
       'P0_SEL', 'TAT', 'TBV_SEL', 'TRA_SEL', 'T25_SEL', 'T3_SEL', 'VBV_SEL',
       'VIB_CN1', 'VIB_CN2', 'VIB_TN1', 'VIB_TN2', 'VSV_SEL', 'WFM_SEL', 'XM'],
      dtype='object')

Les colonnes des DF sont typées, à la manière d'une base de données relationnelle, contrairement aux variables python classiques. Les types des colonnes sont accessibles via df.dtypes. Les principaux types sont les numériques (int32, int64, float etc.

In [107]:
df.loc[10:15, ['EGT_SEL', 'FLIGHT_MOD']]

EGT_SEL FLIGHT_MOD
10    0.00234327        NaN
11  1.08032e-007        NaN
12  3.12514e-012        NaN
13             0        NaN
14       72.0006        NaN
15       215.996        NaN

"""
EXERCICE - Extraction et suppression des unités
On remarque que la 1ère ligne ne contient pas de données mais les unités de chaque colonne.
Pour la suite des traitements, il faut supprimer cette ligne. On souhaite toutefois garder l'information des unités de chaque colonne.
1. Récupérez les unités et stockez les dans une structure adaptée.
2. Supprimez cette ligne du DataFrame en utilisant la méthode "drop"
"""


In [109]:
#recupération et stockage
units = list(df.iloc[0])
#suppresion
df=df.drop(0)
#raise NotImplementedError

In [110]:
print(units)
df.head()

['datenum', 'deg_C', '_', '_', '%', '%', '%', '%_RPM', 'psi', '_', 'psi', 'mb', 'psi', 'deg_C', '%', 'DEG', '_', '_', 'DEG', '_', '_', '_', '_', 'DEG', 'lb/h', 'mach']


t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   
5  15/09/2011 14:25:59.125     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL    OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1  \
1    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
2    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
3    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
4    NaN         0      NaN      NaN  ...     NaN    NaN     NaN     NaN   
5      0         0  647.998      NaN  ...     NaN    NaN       0       0   

  VIB_CN2 VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
1     NaN     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN     NaN  7679.98  0.15  
5       0       0       0       0  4607.86  0.15  

[5 rows x 26 columns]

On remarque que toutes les colonnes ont été reconnues comme de type object, c'est-à-dire des chaînes de caractères, alors que ce sont des valeurs numériques. Cela est dû à la première ligne contenant les unités. Il faut donc convertir les colonnes en numérique. La colonne 't', quant à elle, doit être convertie en type datetime.

In [112]:
df['t'] = pd.to_datetime(df['t'])
df[df.columns[1:]] = df[df.columns[1:]].apply(pd.to_numeric)

C:\Users\jalil\AppData\Local\Temp\ipykernel_7360\2306591669.py:1: UserWarning: Parsing dates in %d/%m/%Y %H:%M:%S.%f format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['t'] = pd.to_datetime(df['t'])


In [113]:
df.dtypes

t             datetime64[ns]
EGT_SEL              float64
FLIGHT_MOD           float64
FMV_SEL              float64
HPTC_SEL             float64
LPTC_SEL             float64
N1_SEL               float64
N2_ACTSEL            float64
OIL_P                float64
OIL_TEMP             float64
PS3_SEL              float64
PT2_SEL              float64
P0_SEL               float64
TAT                  float64
TBV_SEL              float64
TRA_SEL              float64
T25_SEL              float64
T3_SEL               float64
VBV_SEL              float64
VIB_CN1              float64
VIB_CN2              float64
VIB_TN1              float64
VIB_TN2              float64
VSV_SEL              float64
WFM_SEL              float64
XM                   float64
dtype: object

"""
Exercice - Index temporel
Comme nos données sont une série temporelle multivariée, on souhaite utiliser un index temporel.
1. Créez une copie de df, appelée df2, à l'aide de la méthode du même nom.
2. Affectez la colonne du temps ('t') en tant qu'indice du DataFrame.
3. Supprimez la colonne 't' du DF résultant.
"""
raise NotImplementedError

In [115]:
#création d'une copie
df2=df.copy()
print(type(df2))




<class 'pandas.core.frame.DataFrame'>


In [116]:
#affectation colonne et suppression
df2 = df2.set_index('t') 

On constate que pandas a automatiquement reconnu un DatetimeIndex, adapté pour des manipulations de séries temporelles (moyennes glissantes, etc) !

### Valeurs manquantes

**NaN = Not a Number**

Les valeurs NaN doivent être éliminées ou imputées (i.e. remplacées par une certaine valeur) avant la suite des traitements. Ce choix dépend du cas d'usage. Dans un premier temps, nous allons apprendre à :

* trouver les données manquantes (méthode `isna`)
* éliminer les données manquantes d'un DataFrame (méthode `dropna`)
* les remplacer par une constante (méthode (`fillna`)

"""
EXERCICE - La méthode isna
1. Testez la méthode isna sur le DataFrame df2, puis sur une colonne ou une ligne. Que renvoie-t-elle ?
2. En appliquant les méthodes any(axis=...), mean() et max()/idxmax() sur les résultats de isna(), répondez aux questions suivantes :
    2.1 Quelles colonnes contiennent des valeurs manquantes, lesquelles n'en contiennent pas ?
    2.2 Quel est le pourcentage de valeurs manquantes dans le DF (a) par colonne (b) globalement ? Quelle variable contient le plus de NaN ?
    2.3 Quel est le pourcentage d'indices du DF pour lesquels toutes les variables sont présentes ?
"""
print('Question 2.1')
raise NotImplementedError
print('Question 2.2')
raise NotImplementedError
print('Question 2.3')
raise NotImplementedError

In [120]:
#question1
df2.isna()


EGT_SEL  FLIGHT_MOD  FMV_SEL  HPTC_SEL  LPTC_SEL  \
t                                                                           
2011-09-15 14:25:58.125     True        True     True      True      True   
2011-09-15 14:25:58.375     True        True     True      True      True   
2011-09-15 14:25:58.625     True        True     True      True      True   
2011-09-15 14:25:58.875     True        True     True      True      True   
2011-09-15 14:25:59.125     True        True     True      True      True   
...                          ...         ...      ...       ...       ...   
2011-09-15 16:01:32.875     True        True     True      True      True   
2011-09-15 16:01:33.125     True        True     True      True      True   
2011-09-15 16:01:33.375     True        True     True      True      True   
2011-09-15 16:01:33.625     True        True     True      True      True   
2011-09-15 16:01:33.875     True        True     True      True      True   

                         N1_SEL  N2_ACTSEL  OIL_P  OIL_TEMP  PS3_SEL  ...  \
t                                                                     ...   
2011-09-15 14:25:58.125    True      False   True      True     True  ...   
2011-09-15 14:25:58.375    True      False   True      True     True  ...   
2011-09-15 14:25:58.625    True      False   True      True     True  ...   
2011-09-15 14:25:58.875    True      False   True      True     True  ...   
2011-09-15 14:25:59.125   False      False  False      True    False  ...   
...                         ...        ...    ...       ...      ...  ...   
2011-09-15 16:01:32.875    True       True   True      True     True  ...   
2011-09-15 16:01:33.125    True       True   True      True     True  ...   
2011-09-15 16:01:33.375    True       True   True      True     True  ...   
2011-09-15 16:01:33.625    True       True   True      True     True  ...   
2011-09-15 16:01:33.875    True       True   True      True     True  ...   

                         T25_SEL  T3_SEL  VBV_SEL  VIB_CN1  VIB_CN2  VIB_TN1  \
t                                                                              
2011-09-15 14:25:58.125     True    True     True     True     True     True   
2011-09-15 14:25:58.375     True    True     True     True     True     True   
2011-09-15 14:25:58.625     True    True     True     True     True     True   
2011-09-15 14:25:58.875     True    True     True     True     True     True   
2011-09-15 14:25:59.125     True    True    False    False    False    False   
...                          ...     ...      ...      ...      ...      ...   
2011-09-15 16:01:32.875     True    True     True     True     True     True   
2011-09-15 16:01:33.125     True    True     True     True     True     True   
2011-09-15 16:01:33.375     True    True     True     True     True     True   
2011-09-15 16:01:33.625     True    True     True     True     True     True   
2011-09-15 16:01:33.875     True    True     True     True     True     True   

                         VIB_TN2  VSV_SEL  WFM_SEL     XM  
t                                                          
2011-09-15 14:25:58.125     True     True     True   True  
2011-09-15 14:25:58.375     True     True     True   True  
2011-09-15 14:25:58.625     True     True     True   True  
2011-09-15 14:25:58.875     True     True    False  False  
2011-09-15 14:25:59.125    False    False    False  False  
...                          ...      ...      ...    ...  
2011-09-15 16:01:32.875     True     True     True   True  
2011-09-15 16:01:33.125     True     True     True   True  
2011-09-15 16:01:33.375     True     True     True   True  
2011-09-15 16:01:33.625     True     True     True   True  
2011-09-15 16:01:33.875     True     True     True   True  

[22944 rows x 25 columns]

In [121]:
#sur une ligne
val_nan_line=df2.iloc[1].isna()
print(val_nan_line)

EGT_SEL        True
FLIGHT_MOD     True
FMV_SEL        True
HPTC_SEL       True
LPTC_SEL       True
N1_SEL         True
N2_ACTSEL     False
OIL_P          True
OIL_TEMP       True
PS3_SEL        True
PT2_SEL        True
P0_SEL         True
TAT            True
TBV_SEL        True
TRA_SEL        True
T25_SEL        True
T3_SEL         True
VBV_SEL        True
VIB_CN1        True
VIB_CN2        True
VIB_TN1        True
VIB_TN2        True
VSV_SEL        True
WFM_SEL        True
XM             True
Name: 2011-09-15 14:25:58.375000, dtype: bool


elle renvoie true si il y'a une valeur manquante et false si il n'y en a pas.

In [123]:
#question 2.1
colonnes_na = df2.isna().any(axis=0)

# Affichage du résultat
print("Colonnes avec valeurs manquantes (True si au moins une valeur manquante) :")
print(colonnes_na)

Colonnes avec valeurs manquantes (True si au moins une valeur manquante) :
EGT_SEL       True
FLIGHT_MOD    True
FMV_SEL       True
HPTC_SEL      True
LPTC_SEL      True
N1_SEL        True
N2_ACTSEL     True
OIL_P         True
OIL_TEMP      True
PS3_SEL       True
PT2_SEL       True
P0_SEL        True
TAT           True
TBV_SEL       True
TRA_SEL       True
T25_SEL       True
T3_SEL        True
VBV_SEL       True
VIB_CN1       True
VIB_CN2       True
VIB_TN1       True
VIB_TN2       True
VSV_SEL       True
WFM_SEL       True
XM            True
dtype: bool


In [124]:
#question 2.2
# Calcul de la proportion de valeurs manquantes par colonne
proportion_na_col = df2.isna().mean()

# Affichage du résultat
print("Proportion de valeurs manquantes par colonne :")
print(proportion_na_col)

# Calcul de la proportion de valeurs manquantes globale
proportion_na_glob = df2.isna().mean().mean()

# Affichage du résultat
print(f"Proportion de données manquantes globalement : {proportion_na_glob:.2%}")

#variable qui contient le plus de NAN
# Calculer le nombre de valeurs manquantes par colonne
nombre_na_par_colonne = df2.isna().sum()

# Identifier la colonne avec le plus de NaN
colonne_max_na = nombre_na_par_colonne.idxmax()

# Afficher la colonne avec le plus de NaN
print(f"La colonne avec le plus de NaN est : {colonne_max_na}")


Proportion de valeurs manquantes par colonne :
EGT_SEL       0.003487
FLIGHT_MOD    0.004446
FMV_SEL       0.004446
HPTC_SEL      0.004228
LPTC_SEL      0.004576
N1_SEL        0.004184
N2_ACTSEL     0.002528
OIL_P         0.003792
OIL_TEMP      0.003835
PS3_SEL       0.003007
PT2_SEL       0.003705
P0_SEL        0.003705
TAT           0.003007
TBV_SEL       0.002964
TRA_SEL       0.003007
T25_SEL       0.004707
T3_SEL        0.004707
VBV_SEL       0.002920
VIB_CN1       0.002920
VIB_CN2       0.002833
VIB_TN1       0.002833
VIB_TN2       0.002833
VSV_SEL       0.002746
WFM_SEL       0.002702
XM            0.002615
dtype: float64
Proportion de données manquantes globalement : 0.35%
La colonne avec le plus de NaN est : T25_SEL


In [125]:
#question 2.3
# Identifier les lignes sans aucune valeur manquante
lignes_completes = ~df2.isna().any(axis=1)

# Calculer le pourcentage de lignes complètes
pourcentage_lignes_completes = lignes_completes.mean() * 100

# Afficher le pourcentage
print(f"Pourcentage d'indices avec toutes les variables présentes : {pourcentage_lignes_completes:.2f}%")

Pourcentage d'indices avec toutes les variables présentes : 99.48%


"""
EXERCICE - La méthode dropna
La méthode dropna permet d'éliminer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. À quoi correspondent les arguments "axis" et "how" ?
2. Éliminez toutes les lignes contenant uniquement des valeurs manquantes.
3. Éliminez toutes les lignes contenant au moins une valeur manquante. Combien y a-t-il de lignes de différence ?
4. Éliminez toutes les colonnes contenant au moins une valeur manquante.
"""
raise NotImplementedError

#question 1

axis correspond aux index ou aux colonnes
how determine si la ligne ou colonne est enlevée du dataframe si elle contient au moins une donnée manquante ou si toutes les données sont manquantes.

In [128]:
#question 2
df2_sans_tout_na=df2.dropna(axis=0,how='all')

In [129]:
#question 3
df2_sans_une_na=df2.dropna(axis=0,how='any')
#difference
diff_lignes = len(df2_sans_tout_na) - len(df2_sans_une_na)
print(f"Différence de lignes : {diff_lignes}")


Différence de lignes : 64


In [130]:
#question 4
df2_sans_une_na_col=df2.dropna(axis=1,how='any')
df2_sans_une_na_col

Empty DataFrame
Columns: []
Index: [2011-09-15 14:25:58.125000, 2011-09-15 14:25:58.375000, 2011-09-15 14:25:58.625000, 2011-09-15 14:25:58.875000, 2011-09-15 14:25:59.125000, 2011-09-15 14:25:59.375000, 2011-09-15 14:25:59.625000, 2011-09-15 14:25:59.875000, 2011-09-15 14:26:00.125000, 2011-09-15 14:26:00.375000, 2011-09-15 14:26:00.625000, 2011-09-15 14:26:00.875000, 2011-09-15 14:26:01.125000, 2011-09-15 14:26:01.375000, 2011-09-15 14:26:01.625000, 2011-09-15 14:26:01.875000, 2011-09-15 14:26:02.125000, 2011-09-15 14:26:02.375000, 2011-09-15 14:26:02.625000, 2011-09-15 14:26:02.875000, 2011-09-15 14:26:03.125000, 2011-09-15 14:26:03.375000, 2011-09-15 14:26:03.625000, 2011-09-15 14:26:03.875000, 2011-09-15 14:26:04.125000, 2011-09-15 14:26:04.375000, 2011-09-15 14:26:04.625000, 2011-09-15 14:26:04.875000, 2011-09-15 14:26:05.125000, 2011-09-15 14:26:05.375000, 2011-09-15 14:26:05.625000, 2011-09-15 14:26:05.875000, 2011-09-15 14:26:06.125000, 2011-09-15 14:26:06.375000, 2011-09-15 14:26:06.625000, 2011-09-15 14:26:06.875000, 2011-09-15 14:26:07.125000, 2011-09-15 14:26:07.375000, 2011-09-15 14:26:07.625000, 2011-09-15 14:26:07.875000, 2011-09-15 14:26:08.125000, 2011-09-15 14:26:08.375000, 2011-09-15 14:26:08.625000, 2011-09-15 14:26:08.875000, 2011-09-15 14:26:09.125000, 2011-09-15 14:26:09.375000, 2011-09-15 14:26:09.625000, 2011-09-15 14:26:09.875000, 2011-09-15 14:26:10.125000, 2011-09-15 14:26:10.375000, 2011-09-15 14:26:10.625000, 2011-09-15 14:26:10.875000, 2011-09-15 14:26:11.125000, 2011-09-15 14:26:11.375000, 2011-09-15 14:26:11.625000, 2011-09-15 14:26:11.875000, 2011-09-15 14:26:12.125000, 2011-09-15 14:26:12.375000, 2011-09-15 14:26:12.625000, 2011-09-15 14:26:12.875000, 2011-09-15 14:26:13.125000, 2011-09-15 14:26:13.375000, 2011-09-15 14:26:13.625000, 2011-09-15 14:26:13.875000, 2011-09-15 14:26:14.125000, 2011-09-15 14:26:14.375000, 2011-09-15 14:26:14.625000, 2011-09-15 14:26:14.875000, 2011-09-15 14:26:15.125000, 2011-09-15 14:26:15.375000, 2011-09-15 14:26:15.625000, 2011-09-15 14:26:15.875000, 2011-09-15 14:26:16.125000, 2011-09-15 14:26:16.375000, 2011-09-15 14:26:16.625000, 2011-09-15 14:26:16.875000, 2011-09-15 14:26:17.125000, 2011-09-15 14:26:17.375000, 2011-09-15 14:26:17.625000, 2011-09-15 14:26:17.875000, 2011-09-15 14:26:18.125000, 2011-09-15 14:26:18.375000, 2011-09-15 14:26:18.625000, 2011-09-15 14:26:18.875000, 2011-09-15 14:26:19.125000, 2011-09-15 14:26:19.375000, 2011-09-15 14:26:19.625000, 2011-09-15 14:26:19.875000, 2011-09-15 14:26:20.125000, 2011-09-15 14:26:20.375000, 2011-09-15 14:26:20.625000, 2011-09-15 14:26:20.875000, 2011-09-15 14:26:21.125000, 2011-09-15 14:26:21.375000, 2011-09-15 14:26:21.625000, 2011-09-15 14:26:21.875000, 2011-09-15 14:26:22.125000, 2011-09-15 14:26:22.375000, 2011-09-15 14:26:22.625000, 2011-09-15 14:26:22.875000, ...]

[22944 rows x 0 columns]

"""
EXERCICE - La méthode fillna
La méthode dropna permet d'imputer les valeurs manquantes (NaN). Lisez d'abord sa documentation.
1. Quelles sont les différentes stratégies de remplissage des valeurs manquantes ?
2. Imputez les valeurs manquantes de la colonne age du DF donné en exemple par :
    - 0
    - la dernière valeur précédente/suivante valide
    - la moyenne
    - la valeur la plus courante (mode)
3. Quel est le meilleur choix dans ce cas ? Et pour le cas d'une variable temporelle, par exemple la température 'EGT_SEL' de notre jeu de données ?
"""
exemple = pd.DataFrame({'nom': ['Alice', 'Bob', 'Charlie', 'David'], 'age': [24, pd.np.nan, 99, 24]})

raise NotImplementedError

#question 1

Remplissage avec une valeur spécifique (ex scalaire).
Remplissage en avant.
Remplissage en arrière.
Limitation du nombre de remplissages.
Remplissage basé sur des groupes.




In [133]:
#question 2
import pandas as pd
import numpy as np

# Création du DataFrame
exemple = pd.DataFrame({'nom': ['Alice', 'Bob', 'Charlie', 'David'], 'age': [24, np.nan, 99, 24]})

# Affichage du DataFrame original
print("DataFrame original :")
print(exemple)

# Imputation avec 0
exemple_zero = exemple.copy()
exemple_zero['age'] = exemple_zero['age'].fillna(0)
print("\nImputation avec 0 :")
print(exemple_zero)

# Imputation avec la dernière valeur précédente 
exemple_ffill = exemple.copy()
exemple_ffill['age'] = exemple_ffill['age'].fillna(method='ffill')
print("\nImputation avec la dernière valeur précédente :")
print(exemple_ffill)

# Imputation avec la prochaine valeur valide 
exemple_bfill = exemple.copy()
exemple_bfill['age'] = exemple_bfill['age'].fillna(method='bfill')
print("\nImputation avec la prochaine valeur valide :")
print(exemple_bfill)

# Imputation avec la moyenne
moyenne_age = exemple['age'].mean()
exemple_mean = exemple.copy()
exemple_mean['age'] = exemple_mean['age'].fillna(moyenne_age)
print("\nImputation avec la moyenne :")
print(exemple_mean)

# Imputation avec le mode
mode_age = exemple['age'].mode()[0]
exemple_mode = exemple.copy()
exemple_mode['age'] = exemple_mode['age'].fillna(mode_age)
print("\nImputation avec le mode :")
print(exemple_mode)


DataFrame original :
       nom   age
0    Alice  24.0
1      Bob   NaN
2  Charlie  99.0
3    David  24.0

Imputation avec 0 :
       nom   age
0    Alice  24.0
1      Bob   0.0
2  Charlie  99.0
3    David  24.0

Imputation avec la dernière valeur précédente :
       nom   age
0    Alice  24.0
1      Bob  24.0
2  Charlie  99.0
3    David  24.0

Imputation avec la prochaine valeur valide :
       nom   age
0    Alice  24.0
1      Bob  99.0
2  Charlie  99.0
3    David  24.0

Imputation avec la moyenne :
       nom   age
0    Alice  24.0
1      Bob  49.0
2  Charlie  99.0
3    David  24.0

Imputation avec le mode :
       nom   age
0    Alice  24.0
1      Bob  24.0
2  Charlie  99.0
3    David  24.0


C:\Users\jalil\AppData\Local\Temp\ipykernel_7360\1138228211.py:20: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  exemple_ffill['age'] = exemple_ffill['age'].fillna(method='ffill')
C:\Users\jalil\AppData\Local\Temp\ipykernel_7360\1138228211.py:26: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  exemple_bfill['age'] = exemple_bfill['age'].fillna(method='bfill')


#question 3

#La strategie de la dernière valeur précedente est la meilleure.
#pour notre jeu de données, la strategie Moyenne est la meilleure.

## Git

Créer un compte GitHub : https://github.com/

Créer un nouveau repository :
1. Sélectionner "Nouveau dépôt" dans le menu déroulant avec le signe +. 
2. Saisisser un nom pour votre dépôt (par exemple, "TDs statistiques descriptives") 
3. Cliquer sur "Créer un dépôt". Ne vous souciez pas des autres options.



Télécharger Git Bash : https://git-scm.com/downloads

Sur Git Bash, positionnez-vous dans le répertoire où votre projet figure.

Ensuite

> git init

> git remote add origin https://github.com/********

> git add .

> git commit -m "Ajout du TD1"

> git push origin master

C'est tout ! Vous avez créé votre repo GitHub ! 